server:
  port: 8082

spring:
  application:
    name: ace-workflow
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_workflow?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    pool:
        max-active: 20

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.wf
    title: ace-workflow
    version: 1.0.0.SNAPSHOT
    description: 工作流服务
    contact:
        name: workflow


# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-workflow
    secret: 123456
    token-header: client-token

logging:
  level:
    com.github.wxiaoqi.security.wf: debug
#    org.activiti: debug
#    org.framework: debug