logging:
    level:
#        tk.mybatis: DEBUG
        com.github.wxiaoqi.oss: DEBUG
server:
    port: 9991

spring:
    profiles:
      active: dev
    application:
        name: ace-gate
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.oss
    title: ace-gate
    version: 1.0.0.SNAPSHOT
    description: sssssssssqqqqqq
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-tool
    secret: 123456
    token-header: client-token
    
mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper

# 具体看类:CloudStorageConfig
oss:
  type: 1 # 类型 1：七牛  2：阿里云  3：腾讯云
  qiniuDomain: http://xxxxx
  qiniuPrefix: xxx
  qiniuAccessKey: xxxxx
  qiniuSecretKey: xxxxx
  qiniuBucketName: xxxx

search:
  lucence:
    path: ./lucence/file